---
title: "final"
author: "Ting-fen Lin"
date: "2/21/2019"
output: pdf_document
---

```{r setup, include = TRUE, echo = TRUE}
library("dplyr")
library("tidyverse")
library("rio")
library("here")
library("forcats")
library("fivethirtyeight")
library("wesanderson")
library("ggplot2")
library("gdata")
library("viridis")
library("colorblindr")
library("stringr")
library("tidytext")
library("kableExtra")
library("formattable")
library("flextable")

knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      error = TRUE,
                      fig.width = 6.5,
                      fig.height = 8
                      )
theme_set(theme_minimal(base_size = 8))
```


```{r resize}
# Resize plot
knitr::opts_chunk$set(fig.width=12, fig.height=8) 
```


```{r demographics}
SKY <- import(here("data", "survey.xlsx"), setclass = "tbl_df") 

str(SKY)

#original
#Fig1.1
ggplot(SKY, aes(x = Category)) +
  geom_histogram(stat = "Count",
                 fill = "#56B4E9",
                 color = "white",
                 alpha = 0.7) +
   theme_minimal(base_size = 15)


#original
#Fig1.2
SKY

SKY %>% 
  mutate(Category = factor(Category, 
                           levels = c("Graduate",
                                      "Community member", 
                                      "Faculty/Staff",
                                      "Undergrad",
                                      "Post-bach"))) %>% 

ggplot(aes(x = Category)) +
  geom_histogram(stat = "count",
                 color = "white",
                 alpha = 0.7) +
  scale_y_continuous(breaks = seq(0, 11, by = 1)) +
  scale_fill_OkabeIto() +
  coord_flip() +
  labs(x = "Category",
       y = "Count",
       title = "Where are the participants from?") +
    theme_minimal(base_size = 15)  + 
  theme(panel.grid.minor = element_line(linetype = "blank"))

...............
#updated
#Fig1.3
SKY %>% 
  count(Category) %>% 
  ggplot(aes(x = fct_reorder(Category, n), n)) +
  geom_col(aes(fill = Category),
           color = "white",
           alpha = 0.7) +
  scale_y_continuous(breaks = seq(0, 11, by = 1),
                     limits = c(0, 10.25)) +
  scale_fill_OkabeIto() +
  coord_flip(expand = FALSE) +
  labs(x = "Category",
       y = "Count",
       title = "Where are the participants from?") +
  theme_minimal(base_size = 15)  + 
  theme(panel.grid.minor = element_line(linetype = "blank")) +
  guides(fill = "none")

```


```{r survey recommend}
library(ggridges)

#original
#Fig 2.1
ggplot(SKY, x = 0:5, aes(Recommend, Category)) +
   ggridges::geom_density_ridges(color = "white",
                                alpha = 0.4) +
  scale_color_OkabeIto() +
    labs(x = "Strongly Disagree - Strongly Agree",
       y = "Category",
       title = "I would recommend this training to my peers as they would benefit from it")  +
  theme_minimal(base_size = 15)

...............
#updated
#Fig 2.2
ggplot(SKY, aes(Recommend)) +
  geom_dotplot(aes(fill = Category), 
               stackgroups = TRUE,
               binwidth = 0.3) +
  scale_fill_OkabeIto() +
  scale_x_continuous(breaks = 0:6, limits = c(0, 6),
                     labels=c("0" = "", 
                              "1" = "Strongly Disagree",
                              "2" = "Disagree", 
                              "3" = "Neutral",
                              "4" = "Agree", 
                              "5" = "Strongly Agree",
                              "6" = "")) +
  scale_y_continuous(labels=c("0.00" = "0", 
                              "0.25" = "6",
                              "0.50" = "12", 
                              "0.75" = "18",
                              "1.00" = "24")) +
   coord_flip() +
   coord_flip(expand = FALSE) +
   theme_minimal(base_size = 15) +
  theme(panel.grid.minor = element_line(linetype = "blank")) +
  labs(x = NULL, 
       y = NULL, 
       title = "I would recommend this training to my peers as they would benefit",
       subtitle = "N = 21")+
  labs(y = "Number of Participants")



```


```{r survey response quantitative}
#original
Fig3.1 <- ggplot(SKY, aes(x = Name, y = energy)) +
   geom_point() +
  coord_flip() +
  labs(x = "Participant",
       y = "Strongly Disagree - Strongly Agree",
       title = "The Retreat has increased my energy levels") +
    theme_minimal(base_size = 15)
Fig3.1 + ylim(0, 5)

Fig3.2 <- ggplot(SKY, aes(x = Name, y = clarity_mind)) +
  geom_point() +
  coord_flip() +
    labs(x = "Participant",
       y = "Strongly Disagree - Strongly Agree",
       title = "The Retreat has enhanced my clarity of mind") +
    theme_minimal(base_size = 15)
Fig3.2 + ylim(0, 5)

Fig3.3 <- ggplot(SKY, aes(x = Name, y = multiple_responsibilities)) +
  geom_point() +
  coord_flip() +
    labs(x = "Participant",
       y = "Strongly Disagree - Strongly Agree",
       title = "The Retreat has increased my ability to manage multiple responsibilities") +
    theme_minimal(base_size = 15)
Fig3.3 + ylim(0, 5)

Fig3.4 <- ggplot(SKY, aes(x = Name, y = connect_to_myself)) +
  geom_point() +
  coord_flip() +
    labs(x = "Participant",
       y = "Strongly Disagree - Strongly Agree",
       title = "The Retreat has enhanced my ability to connect to myself") +
    theme_minimal(base_size = 15)
Fig3.4 + ylim(0, 5)

Fig3.5 <- ggplot(SKY, aes(x = Name, y = stay_focused)) +
  geom_point() +
  coord_flip() +
    labs(x = "Participant",
       y = "Strongly Disagree - Strongly Agree",
       title = "The Retreat has increased my ability to stay focused on the task at hand") +
    theme_minimal(base_size = 15)
Fig3.5 + ylim(0, 5)


Fig3.6 <- ggplot(SKY, aes(x = Name, y = remain_calm)) +
  geom_point() +
  coord_flip() +
    labs(x = "Participant",
       y = "Strongly Disagree - Strongly Agree",
       title = "The Retreat has improved my ability to remain calm in difficult situations") +
    theme_minimal(base_size = 15)
Fig3.6 + ylim(0, 5)

Fig3.7 <- ggplot(SKY, aes(x = Name, y = gain_resilience)) +
  geom_point() +
  coord_flip() +
    labs(x = "Participant",
       y = "Strongly Disagree - Strongly Agree",
       title = "The Retreat has increased my ability to gain resilience")+
    theme_minimal(base_size = 15) 
Fig3.7 + ylim(0, 5)

Fig3.8 <- ggplot(SKY, aes(x = Name, y = broader_perspectives)) +
  geom_point() +
  coord_flip() +
    labs(x = "Participant",
       y = "Strongly Disagree - Strongly Agree",
       title = "The Retreat has increased my ability to gain broader perspectives when facing challenging situations") +
    theme_minimal(base_size = 15)
Fig3.8 + ylim(0, 5)

Fig3.9 <- ggplot(SKY, aes(x = Name, y = connect_with_others)) +
  geom_point() +
  coord_flip() +
    labs(x = "Participant",
       y = "Strongly Disagree - Strongly Agree",
       title = "The Retreat has increased my ability to connect with others") +
    theme_minimal(base_size = 15)
Fig3.9 + ylim(0, 5)


Fig3.10 <-ggplot(SKY, aes(x = Name, y = good_investment_of_time)) +
  geom_point() +
  coord_flip() +
    labs(x = "Participant",
       y = "Strongly Disagree - Strongly Agree",
       title = "The Retreat is a good investment of time") +
    theme_minimal(base_size = 15)
Fig3.10 + ylim(0, 5)

...............
#updated
SKY %>%
  count(energy) %>%
  mutate(prop = 100*n/sum(n-1)) 

SKY %>%
  count(clarity_mind) %>%
  mutate(prop = 100*n/sum(n-1))

SKY %>%
  count(multiple_responsibilities) %>%
  mutate(prop = 100*n/sum(n-1))
  
SKY %>%
  count(connect_to_myself) %>%
  mutate(prop = 100*n/sum(n-1))

SKY %>%
  count(stay_focused) %>%
  mutate(prop = 100*n/sum(n-1))

SKY %>%
  count(remain_calm) %>%
  mutate(prop = 100*n/sum(n-1))

SKY %>%
  count(gain_resilience) %>%
  mutate(prop = 100*n/sum(n-1))


SKY %>%
  count(broader_perspectives) %>%
  mutate(prop = 100*n/sum(n-1))

SKY %>%
  count(connect_with_others) %>%
  mutate(prop = 100*n/sum(n-1))


SKY2 <- import(here("data", "SKY2.xlsx"), setclass = "tbl_df") 

SKY2 %>% 
  kable() %>% 
   kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive", full_width = NULL, position = "left")) %>% 
  column_spec(6:6, bold = T, color = "#3A9E23", background = "#F8F668") %>%
   footnote(general = "The participants were asked to rate how the techniques taught in the SKY Happiness Retreat have the ability to impact different areas.",
            number = c("Numbers are in percentage"))

```




```{r survey response qualitative 1}
#still working to get this graph to show - would appreciate comments

experience <- c("I thought it was positive and powerful",
                "It was very beautiful. It felt like truth",
                "Fantastic growth experience",
                "Wonderful! There were physically challenging moments while sitting for Sudarshan Kriya but I benefited a lot & have smiled more during this retreat than I have in a month",
                "I had a wonderful experience. I had been feeling very unbalanced and uncertain. I now feel much better and more centered",
                "I feel empowered and enlightened",
                "Very positive! Uplifting. Beautiful. Meaningful",
                "Great! I feel more relaxed, confident & can concentrate more on what I am doing",
                "So positive! I feel more capable of managing the things that come my way, and more open to others",
                "It was enlightening and freeing",
                "It was completely transformative. I LOVED it and felt so grateful for Sarah and Ting-fen and all their knowledge",
                "Wonderful!",
                "Kind. Open. Good experience",
                "Very positive, nurturing, and invigorating",
                "Nice. Learned so many new things",
                "Very positive and good use of time",
                "Amazing! So calming, welcoming, and educational",
                "Pretty amazing",
                "Amazing",
                "I enjoyed it",
                "It was great")

experience_df <- tibble(line = 1:21, text = experience)

experience_df <- experience_df %>%
  unnest_tokens(word, text)

data(stop_words)

experience_df <- experience_df %>%
  anti_join(stop_words)

experience_df %>%
  count(word, sort = TRUE)

#original
experience_df  %>%
  count(word, sort = TRUE) %>%
  filter (n > 1) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip() +
    theme_minimal(base_size = 15)
  
...............
#updated
experience_df  %>%
  count(word, sort = TRUE) %>%
  filter (n > 1) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col(fill = "cornflowerblue",
           alpha = 0.7) +
  scale_y_continuous(breaks = seq(0, 11, by = 1),
                     limits = c(0, 5.25)) +
  xlab(NULL) +
  coord_flip() + 
  coord_flip(expand = FALSE) +
  labs(x = "Word Use",
       y = "Frequency Count",
       title = "How was the experiece?") +
    theme_minimal(base_size = 15)  + 
    theme_minimal(base_size = 15)  + 
  theme(panel.grid.minor = element_line(linetype = "blank")) +
  guides(fill = "none") 


```


```{r survey response qualitative 2 - n-gram}

 say_SKY <- c("It's a connection that connects",
          "I would say it is very much worthwhile",
          "Do it! Jump in!",
          "Come with an open mind, leave with an open heart",
          "I would highly encourage anyone to participate. I was able to be open, honest, and vulnerable about my experiences and be fully accepted",
          "It will empower you and change your life",
          "It's more than simply de-stressing. It's learning and adopting a new healthy mental lifestyle",
          "Absolutely go! The time you give to yourself to experience this retreat will help you become a better, fuller human being",
          "How much do you value allowing happiness into your life and the lives of others?",
          "This has been one of the most beautiful life experiences that I will always carry with me! SKY gives you tools to live life more fully",
          "Do it!! Just, do it!",
          "Remember the positivity in yourself and others, and spread to world",
          "It really is helpful for college student stress",
          "Go for it. Things will be better",
          "It is a good use of time",
          "This is such a valuable experience!",
          "Good stepping stones toward peace and love",
          "You should do it. Keep an open mind",
          "If you're willing to practice each day, it will help you",
          "Don't hesitate; meditate. Better get some rotalities :)")

say_df <- tibble(line = 1:20, text = say_SKY)

say_df <- say_SKY() %>%
   unnest_tokens(bigram, text, token = "ngrams", n = 2)

 say_df %>%
   count(bigram, sort = TRUE)

 bigrams_seperated <- say_df %>%
   seperate(bigram, c("word1", "word2"), sep = " ")

 bigrams_filtered <- bigrams_seperated %>%
   filter(!word1 %in% stop_word$word) %>%
   filter(!word2 %in% stop_words$word)

 bigram_counts <- bigram_filtered %>%
   count(word1, word2, sort = TRUE)
 bigram_counts

 bigram_united <- bigram_filtered %>%
   unite(bigram, word1, word2, sep = "")
 bigram_united



 say_df() %>%
   unnest_tokens(trigram, text, token = "ngrams", n = 2) %>%
   separate(trigram, c("word1", "word2"), sep = " ") %>%
   filter(!word1 %in% stop_words$word,
          !word2 %in% stop_words$word) %>%
   count(word1, word2, word3, sort = TRUE)


 say_df() %>%
   unnest_tokens(trigram, text, token = "ngrams", n = 3) %>%
   separate(trigram, c("word1", "word2", "word3"), sep = " ") %>%
   filter(!word1 %in% stop_words$word,
          !word2 %in% stop_words$word,
          !word3 %in% stop_words$word) %>%
   count(word1, word2, word3, sort = TRUE)
 
 
ggplot(aes(word, n)) +
  geom_col(fill = "#CCFB5D",
           alpha = 0.7) +
  scale_y_continuous(breaks = seq(0, 11, by = 1),
                     limits = c(0, 5.25)) +
  xlab(NULL) +
  coord_flip() + 
  coord_flip(expand = FALSE) +
  labs(x = "Phrase Use",
       y = "Frequency Count",
       title = "How would you say to someone considering the Retreat?") +
    theme_minimal(base_size = 15)  + 
    theme_minimal(base_size = 15)  + 
  theme(panel.grid.minor = element_line(linetype = "blank")) +
  guides(fill = "none") 

   
```